<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-07 at 03:29:32.
 */
use PHPUnit\Framework\TestCase;

require __DIR__ . "/../src/Database.php";

class DatabaseTest extends TestCase {

    /**
     * @var Database
     */
    private $db = null;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->db = new Database;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->db);
    }

    /**
     * @covers Database::reallyLongTime
     * @todo   Implement testReallyLongTime().
     */
    public function testReallyLongTime() {
        $mock = $this->createMock(Database::class);
        $results = array(
            array(1, 'test', 'foo value')
        );

        $mock->expects($this->any())->
                method('reallyLongTime')->
                will($this->returnvalue($results));
        $return = $mock->reallyLongTime();

        $this->assertGreaterThan(0, count($return));
    }
    
    
    

}
